name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Moved to dev_dependencies properly

# This must be at the very root level (no spaces before it)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image.png"
  adaptive_icon_background: "#1A0dab" # Put your exact hex background color here
  adaptive_icon_foreground: "assets/image2.png" # Make sure your logo is saved exactly here
  min_sdk_android: 21

flutter:
  uses-material-design: true
  # If you want to use this image inside the app UI later, uncomment the lines below:
  # assets:
  #   - assets/image.png